In [4]:
import numpy as np

In [2]:
def sigma_points(X,P,kappa):
    """
    Computes the sigma points and weights for an unscented Kalman filter
given the mean and covariance of the filter.
kappa is an arbitrary constant
constant. Returns tuple of the sigma points and weights.
Works with both scalar and array inputs:
sigma_points (5, 9, 2) # mean 5, covariance 9
sigma_points ([5, 2], 9*eye(2), 2) # means 5 and 2, covariance 9I
Parameters
----------
X An array of the means for each dimension in the problem space.
Can be a scalar if 1D.
examples: 1, [1,2], np.array([1,2])
P : scalar, or
Returns
-------
sigmas : np.array, of size (n, 2n+1)
Two dimensional array of sigma points. Each column contains all of
the sigmas for one dimension in the problem space.
Ordered by Xi_0, Xi_{1..n}, Xi_{n+1..2n}
weights : 1D np.array, of size (2n+1)
    """
    if np.isscalar(X):
        return np.array([X])
    if np.isscalar(P):
        return np.array([[P]])
    """
    Xi: sigma points
    W: weights
    """
    n = np.size(X)
    W = np.full((2*n+1),0.5/(n+kappa))
    Xi = np.zeros((2*n+1,n))
    #Handles values for the mean
    Xi[0] = X
    W[0] = kappa/(n+kappa)
    
    #Implements U'*U = (n+kappa)*P and returns a lower triangular matrix
    #Take transpose so we can access with U[i]
    U = np.linalg.cholesky((n+kappa)*P).T
    for k in range(n):
        Xi[k+1] = X + U[k]
        Xi[n+k+1] = X - U[k]
    return (Xi,W)

In [3]:
def Unscented_transform(Xi,W,NoiseCov = None):
    """
    Returns the mean and covariance in a tuple after computing the unscented transform of a set of sigma points and 
    weights
    """
    kmax,n = Xi.shape
    X = np.sum(Xi*W,axis = 0)
    P = np.zeros((n,n))
    for k in range(kmax):
        s = (Xi[k]-X)[np.newaxis]
        P += W[k]*s*s.T
    if NoiseCov is not None:
        P += NoiseCov
    return (X,P)

In [11]:
#Test
Xi = [[1,2,3],[1,2,3],[1,2,3]]
Xi = np.array(Xi)
print(Xi)
print(np.sum(Xi) == 18)
print(np.sum(Xi,axis = 0) == [3,6,9])
np.sum(Xi,axis = 1) == [6,6,6]

[[1 2 3]
 [1 2 3]
 [1 2 3]]
True
[ True  True  True]


array([ True,  True,  True])